$ErrorActionPreference = 'Continue'

$root = Join-Path $PSScriptRoot '..'

# 在仓库里跑 git：MSBuild 并不保证当前工作目录是哪里。
$tag = (git -C $root describe --always --tags '--abbrev=0' 2>$null)
$revision = (git -C $root describe --always --tags 2>$null)

if ([string]::IsNullOrWhiteSpace($revision)) { $revision = '0' }

# AssemblyVersion 只接受 major[.minor[.build[.revision]]] 格式。没有可达标签时
# `git describe --always` 会退回成提交哈希，而且标签还可能带 "v" 前缀，
# 所以凡是不像纯版本号的都得替换掉，不能直接写出去。
$version = '0.0.0'
if (-not [string]::IsNullOrWhiteSpace($tag)) {
    $candidate = $tag.Trim() -replace '^[vV]', ''
    if ($candidate -match '^\d+(\.\d+){0,3}$') { $version = $candidate }
}

$text = @"
// This file is generated by update-version.ps1

using System.Reflection;

[assembly: AssemblyVersion("$version")]
[assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File (Join-Path $root 'GitVersion.cs') -Encoding utf8

$xml = [xml](Get-Content (Join-Path $root 'QuickLook.Plugin.Metadata.Base.config'))
$xml.Metadata.Version = "$revision"
$xml.Save((Join-Path $root 'QuickLook.Plugin.Metadata.config'))
